//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3tierEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public int MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> Luong { get; set; }
        public string MaPhong { get; set; }
    
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
