//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3tierEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public int MaNhanVien { get; set; }
        public int MaViec { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual VIECLAM VIECLAM { get; set; }
    }
}
